version: "3"

services:
    app:
        build: .
        restart: always
        depends_on:
            - mariadb
        ports: 
            - "8443:443"
    
    mariadb:
        build: mariadb/.
        restart: always
        #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        # volumes:
            # - "mariadb-data:/var/lib/mysql"
