version: "2.1"

services:
    app:
        build: .
        restart: always
        environment:
            PORT: ${PORT}
        depends_on:
            mariadb:
                condition: service_healthy
        ports: 
            - "${PORT}:${PORT}"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
    
    mariadb:
        build: 
            context: mariadb/.
            args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWORD: ${DB_PASSWORD}
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - "mariadb-data:/var/lib/mysql"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"

volumes:
    mariadb-data:
        driver: local
