version: "3"

services:
    app:
        build: .
        restart: always
        depends_on:
            - mariadb
        ports: 
            - "8443:443"
    
    mariadb:
        build: mariadb/.
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - "mariadb-data:/var/lib/mysql"
        command: mysql -D ${DB_NAME} -e "SOURCE ./init.sql"

volumes:
    mariadb-data:
        driver: local