version: "3"

services:
    app:
        build: .
        restart: always
        depends_on:
            - mariadb
        ports: 
            - "8000:8000"
        volumes:
            - .:/app
        command: sh -c "while true ;do sleep 20; done"
    
    mariadb:
        image: "mariadb:latest"
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

