version: "3"

services:
    app:
        image: golang:latest
        depends_on:
            - mariadb
        ports: 
            - "8000:8000"
        networks:
            - backend
        volumes:
                - .:/app
    
    mariadb:
        image: "mariadb:latest"
        restart: unless-stopped
        networks:
            - backend
        