version: "2.1"

services:
    app:
        build: .
        restart: always
        #network_mode: host
        environment:
            PORT: ${PORT}
        depends_on:
            mariadb:
                condition: service_healthy
        ports: 
            - "${PORT}:${PORT}"
        volumes:
            - ".:/app:ro"
            - "/etc/localtime:/etc/localtime:ro"

    mariadb:
        image: mariadb
        #network_mode: host
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - "mariadb-data:/var/lib/mysql"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
        volumes:
            - "./mariadb/init.sh:/docker-entrypoint-initdb.d/init.sh:ro"
            - "./mariadb/init.sql:/init.sql:ro"
            - "/etc/localtime:/etc/localtime:ro"

volumes:
    mariadb-data:
        driver: local
