#! /bin/bash
if [ "$EUID" -ne 0 ]; then 
	echo "Please run as root"
	exit 1
fi
DB_NAME=$1
DB_USER=$2
DB_PASSWORD=$3

mysql -e "
DROP DATABASE IF EXISTS $DB_NAME;
CREATE DATABASE IF NOT EXISTS $DB_NAME; 
DROP USER IF EXISTS '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
FLUSH PRIVILEGES;
GRANT ALL ON $DB_NAME.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
USE $DB_NAME;
SOURCE ./sql-command/init.sql;"